### CREATE five documents.
POST http://localhost:3000/pokemons HTTP/1.1
content-type: application/json

{
    "pokemon": "Pikachu",
    "level": 25,
    "dateCaptured": "2024-05-01"
}


### CREATE 2
POST http://localhost:3000/pokemons HTTP/1.1
content-type: application/json

{
    "pokemon": "Charizard",
    "level": 36,
    "dateCaptured": "2024-04-15"
}

### CREATE 3
POST http://localhost:3000/pokemons HTTP/1.1
content-type: application/json

{
    "pokemon": "Piplup",
    "level": 16,
    "dateCaptured": "2024-03-22"
}

### CREATE 4
POST http://localhost:3000/pokemons HTTP/1.1
content-type: application/json

{
    "pokemon": "Greninja",
    "level": 40,
    "dateCaptured": "2024-01-12"
}

### CREATE 5
POST http://localhost:3000/pokemons HTTP/1.1
content-type: application/json

{
    "pokemon": "Lucario",
    "level": 35,
    "dateCaptured": "2024-01-12"
}


### RETRIEVE all documents.
GET http://localhost:3000/pokemons HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/pokemons/6653a71341eb89c6d5e9dc90 HTTP/1.1


### UPDATE one document's year, by ID.
### Replace the ID in the following request with one that exists
### and update the year:
PUT http://localhost:3000/pokemons/6653a71341eb89c6d5e9dc90 HTTP/1.1
content-type: application/json

{
    "pokemon": "Pikachu",
    "level": 30,
    "dateCaptured": "2024-05-01"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/pokemons/6653a71341eb89c6d5e9dc90 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/pokemons HTTP/1.1

